name: Build Geode Mod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows
            os: windows-latest
            platform: win
          - name: Android
            os: ubuntu-latest
            platform: android

    name: Build ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build Geode Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          platform: ${{ matrix.config.platform }}
